apiVersion: v1
kind: Service
metadata:
  name: hello-minikube-service
  labels:
    app: spring-boot-telekomV01
spec:
  type: LoadBalancer
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
  selector:
    app: spring-boot-telekomV01